spring:
  application:
    name: grocery
  datasource:
    url: jdbc:h2:mem:grocery;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jpa:
    defer-datasource-initialization: true
