INSERT INTO PRODUCT(PRODUCT_CODE,PRODUCT_NAME,PRODUCT_PRICE) values ('CE','Cheese','5.95')
INSERT INTO PRODUCT(PRODUCT_CODE,PRODUCT_NAME,PRODUCT_PRICE) values ('HM','Ham','7.95')
INSERT INTO PACKAGE_OPTIONS(PRODUCT_CODE,QUANTITY,PACKAGE_PRICE) values ('CE','3','14.95')